# Generated by Django 4.0.2 on 2022-04-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('parent_name', models.CharField(max_length=200)),
                ('parent_lname', models.CharField(max_length=200)),
                ('student_id', models.IntegerField(max_length=200)),
                ('phonde', models.CharField(max_length=200)),
            ],
        ),
    ]
