# Generated by Django 4.0.2 on 2022-04-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0003_alter_parent_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
