# Generated by Django 4.0.2 on 2022-04-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0005_student_remove_parent_parent_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
