# Generated by Django 4.0.2 on 2022-04-26 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0006_remove_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='phonde',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms.subject'),
        ),
        migrations.AddField(
            model_name='parent',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_lname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbms.subject'),
        ),
    ]
